# Generated by Django 6.1.1 on 2026-10-01 20:31

import apps.metas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.CharField(db_default=apps.metas.models.ToCharNow(), editable=False, max_length=32)),
                ('nome_participante', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('faturamento', models.FloatField(blank=True, default=0, null=True)),
                ('crescimento_pct', models.FloatField(blank=True, default=0, null=True)),
                ('churn_pct', models.FloatField(blank=True, default=0, null=True)),
                ('ticket', models.FloatField(blank=True, default=0, null=True)),
                ('conversao_pct', models.FloatField(blank=True, default=0, null=True)),
                ('contatos_mes_passado', models.FloatField(blank=True, default=0, null=True)),
                ('hunter_valor', models.FloatField(blank=True, default=0, null=True)),
                ('meta_anual', models.FloatField(blank=True, default=0, null=True)),
                ('meta_trimestral', models.FloatField(blank=True, default=0, null=True)),
                ('meta_mensal', models.FloatField(blank=True, default=0, null=True)),
                ('contratos_mes', models.FloatField(blank=True, default=0, null=True)),
                ('contatos_necessarios', models.FloatField(blank=True, default=0, null=True)),
                ('farmer_valor', models.FloatField(blank=True, default=0, null=True)),
                ('equipe_json', models.TextField(blank=True, default='[]')),
                ('notificado_em', models.CharField(blank=True, editable=False, max_length=32, null=True)),
            ],
            options={
                'db_table': 'metas',
                'managed': False,
            },
        ),
    ]
