# Generated by Django 6.1.1 on 2026-09-22 15:00

import apps.meu_porque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuPorqueResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.CharField(db_default=apps.meu_porque.models.ToCharNow(), editable=False, max_length=32)),
                ('nome_participante', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('sonho', models.TextField(blank=True)),
                ('mudanca', models.TextField(blank=True)),
                ('visao_futuro', models.TextField(blank=True)),
                ('notificado_em', models.CharField(blank=True, editable=False, max_length=32, null=True)),
            ],
            options={
                'db_table': 'meu_porque_respostas',
                'managed': False,
            },
        ),
    ]
