# Generated by Django 6.1.1 on 2026-10-01 22:59

import apps.disc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.CharField(db_default=apps.disc.models.ToCharNow(), editable=False, max_length=32)),
                ('nome_participante', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('d_natural', models.FloatField(blank=True, default=0, null=True)),
                ('i_natural', models.FloatField(blank=True, default=0, null=True)),
                ('s_natural', models.FloatField(blank=True, default=0, null=True)),
                ('c_natural', models.FloatField(blank=True, default=0, null=True)),
                ('d_adaptado', models.FloatField(blank=True, default=0, null=True)),
                ('i_adaptado', models.FloatField(blank=True, default=0, null=True)),
                ('s_adaptado', models.FloatField(blank=True, default=0, null=True)),
                ('c_adaptado', models.FloatField(blank=True, default=0, null=True)),
                ('d_intensidade', models.FloatField(blank=True, default=0, null=True)),
                ('i_intensidade', models.FloatField(blank=True, default=0, null=True)),
                ('s_intensidade', models.FloatField(blank=True, default=0, null=True)),
                ('c_intensidade', models.FloatField(blank=True, default=0, null=True)),
                ('perfil_dominante', models.CharField(blank=True, max_length=16)),
                ('arquetipo', models.CharField(blank=True, max_length=200)),
                ('respostas_json', models.TextField(blank=True, default='{}')),
                ('notificado_em', models.CharField(blank=True, editable=False, max_length=32, null=True)),
            ],
            options={
                'db_table': 'disc_respostas',
                'managed': False,
            },
        ),
    ]
